[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "clui"
version = "3.0.0"
description = "Ultimate CLI Library"

[project.optional-dependencies]
textual = ["textual>=0.50.0"]
clipboard = ["pyperclip"]

[tool.setuptools]
py-modules = ["clui"]
